# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn
    command: yarn run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 4000
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 9005
    onOpen: ignore
  - port: 9099
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint